CREATE SCHEMA IF NOT EXISTS airflow AUTHORIZATION airflow;

CREATE USER dwh_user WITH PASSWORD 'dwh_user';
CREATE SCHEMA IF NOT EXISTS project AUTHORIZATION dwh_user;
GRANT USAGE ON SCHEMA project TO dwh_user;
GRANT CREATE ON SCHEMA project TO dwh_user;
GRANT ALL ON ALL TABLES IN SCHEMA project TO dwh_user;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA project TO dwh_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA project GRANT ALL PRIVILEGES ON TABLES TO dwh_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA project GRANT USAGE ON SEQUENCES TO dwh_user;
